services:
  - type: web
    name: nova-asia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --worker-class eventlet -w 1 wsgi:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: nova-asia-db
          property: connectionString
      - key: TELEGRAM_BOT_TOKEN
        value: 7509433067:AAGoLc1NVWqmgKGcrRVb3DwMh1o5_v5Fyio
      - key: TELEGRAM_CHAT_ID
        value: 8047420957
        key: MAIL_USERNAME
        value: postmaster@mg.novaasia.nl
      - key: MAIL_PASSWORD
        value: db54d6fa02661e1cdaa222787a5dbb73-45de04af-7920c20d
      - key: MAIL_SERVER
        value: smtp.eu.mailgun.org
      - key: MAIL_PORT
        value: 587
      - key: MAIL_DEFAULT_SENDER
        value: orders@novaasia.nl
      - key: MOLLIE_API_KEY
        value: test_E6gVk3tT2Frgdedj9Bcexar82dgUMe
      - key: MOLLIE_REDIRECT_URL
        value: https://novaasia.nl/payment-success
      - key: MOLLIE_WEBHOOK_URL
        value: https://flask-order-api.onrender.com/webhook
    autoDeploy: true   # ✅ 需要顶格对齐 services 的子项
